DicPor={'acrobacia':'acrobacia',
'ejercicio aeróbico':'exercício aeróbico',
 'aikido':'aikido',
 'atletismo':'atletismo',
'béisbol':'beisebol',
 'billar':'bilhar',
 'culturismo':'musculação',
 'bollos':'pãezinhos',
 'boliche':'boliche',
 'saltar al vacio':'pular no vazio',
 'regata':'corrida',
 'piragüismo':'canoagem',
 'entrenamiento cardiovascular':'treino cardio',
'automovilismo':'automobilismo',
 'críquet':'grilo',
 'ciclocrós':'ciclocross',
 'carrera de bicicletas':'corrida de bicicleta',
'curling':'ondulação',
 'dardos':'dardos',
 'buceo':'mergulhando',
 'pesca':'pescaria',
 'sala de futbol':'sala de futebol',
'karting':'karting',
 'ala delta':'para o delta',
 'senderismo':'caminhada',
 'caza':'caçar',
 'hockey sobre hielo':'hockey sobre gelo',
 'kickboxing':'kick boxing',
 'kung fu':'kung fu',
 'lacrosse':'lacrosse',
 'salto de longitud':'salto de longitude',
'artes marciales':'artes marciais',
 'maraton':'maratona',
'motorismo':'automobilismo',
 'automovilismo':'automobilismo',
 'motonáutica':'barco a motor',
'motociclismo':'motociclismo',
 'montañismo':'montanhismo',
 'ciclismo de montaña':'ciclisma da montanha',
 'bola de pintura':'paintball',
 'pádel':'remo',
 'paracaidismo':'paraquedismo',
 'parapente':'parapente',
 'parkour':'parkour',
'salto con pértiga':'salto com vara',
'polo':'pólo',
 'ráquetbol':'raquetebol',
 'canotaje':'rafting',
 'descenso con cuerdas':'descida de corda',
 'gimnasia rítmica':'ginástica ritmica',
 'anillas':'argolas',
 'escalada':'escalando',
'hockey sobre patines':'hóquei em patins',
'saltar la cuerda':'pular la corda',
'correr':'para correr',
'patinaje':'patinação',
 'patineta':'skate',
 'esquí':'esqui',
 'esnórquel':'snorkel',
 'snowboard':'snowboard',
 'softbol':'softball',
 'calabaza':'abóbora',
'estiramiento':'alongamento',
 'sumo':'sumo',
 'navegar':'velejar',
 'trapecio':'trapézio',
 'deportes acuáticos':'esportes aquáticos',
 'levantamiento de pesas':'levantamento de peso',
 'halterofilia':'levantamento de peso',
 'Polo acuático':'polo aquático',
 'tabla a vela' :'sailboard',
 'windsurf':'windsurf',
 'esquí acuático':'esqui aquatico',
 'deportes de invierno':'esportes de inverno',  
 }